name: rail_aid
description: A minimal scaffold of RailAid Flutter app (Firebase-ready)
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  http: ^0.13.5
  image_picker: ^0.8.6
  flutter_local_notifications: ^9.8.0
  geolocator: ^9.0.2
  url_launcher: ^6.1.7
  


  firebase_core: ^3.8.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.0.0 
  firebase_storage: ^12.3.0
  firebase_messaging: ^15.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
